# Generated by Django 5.1 on 2024-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='feret_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='perimeter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
